feat: initial commit ;)
NullMoe/micro_ci pull request #1
Opened 2023-09-17 00:49 UTC by LacticWhale

2023-09-18 09:15 UTC, LacticWhale commented on bin/github/github_client.dart
> +  Future<String> createCommitStatus(String fullName, String sha, CheckStatus status) async {
https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#create-a-commit-status

2023-09-18 16:06 UTC, LacticWhale commented on config.yaml
> +    <<: *build_flutter
Added to roadmap

2023-09-18 19:14 UTC, Zekfad requested changes
Few changes required.

2023-09-18 19:14 UTC, Zekfad commented on lib/src/micro_ci.dart
> +    /// First config initialization is sync.
You may use external logic to load config, especially because you already have reload option.
Add some simple state like, `configState` and 3 states unloaded, loaded, error, this will allow you to clear constructor from any actions and delay file read to when it actually need, also it will remove dependency on config file itself.

2023-09-18 19:14 UTC, Zekfad commented on lib/src/micro_ci.dart
> +    );
Use `fromMap` and configure dart_mappable to accept any map.

2023-09-18 19:14 UTC, Zekfad commented on lib/src/micro_ci.dart
> +              processesOutput += processResult.stderr as String;
Is it really string?

2023-09-18 19:14 UTC, Zekfad commented on lib/src/micro_ci.dart
> +                break;
Add labels to make it easier to understand logic of break.

2023-09-18 19:14 UTC, Zekfad commented on lib/src/micro_ci.dart
> +              // _log(stdout, parameters, 'WARNING! Unknown script was presented in job: $jobName, task: ${task.name}, scriptN: $scriptN!');
Throw unimplemented error or argument error. And probably you should check config on load before actually running it.
Then this will be just a safe guard in case of logic error rather than config error which would be excluded on load check.

2023-09-18 19:14 UTC, Zekfad commented on lib/tools.dart
Empty file?

2023-09-18 19:49 UTC, LacticWhale commented on lib/tools.dart
💀

2023-09-18 19:53 UTC, LacticWhale commented on lib/src/micro_ci.dart
> +              processesOutput += processResult.stderr as String;
it is really string, you can look in docs

2023-09-18 20:30 UTC, LacticWhale commented on lib/src/micro_ci.dart
> +              processesOutput += processResult.stderr as String;
"Standard error from the process. The value used for the stderrEncoding argument to Process.run determines the type. If null was used, this value is of type List<int> otherwise it is of type String."

2023-09-19 21:34 UTC, Zekfad requested changes

2023-09-19 21:34 UTC, Zekfad commented on bin/server.dart
> +    ).addMiddleware(
Extract to function.

2023-09-19 21:34 UTC, Zekfad commented on bin/server.dart
> +          Logger.root.info(message);
Use scoped logger.

2023-09-19 21:34 UTC, Zekfad commented on example.config.yaml
Empty file.

2023-09-19 21:34 UTC, Zekfad commented on lib/src/config/job.dart
>      this.env = const [],
Use hook that will split it to map it will allow to make class constant.

2023-09-19 21:34 UTC, Zekfad commented on lib/src/config/script/script.dart
> +  ],
Remove.

2023-09-19 21:34 UTC, Zekfad commented on lib/src/config/task.dart
>      this.env = const [],
Same as with job, use same hook and make class const.

2023-09-19 21:34 UTC, Zekfad commented on lib/src/config_watcher.dart
> +    _logger.config('config.yaml was updated.');
Hardcoded name. Use configFile path.

2023-09-19 21:34 UTC, Zekfad commented on lib/src/job_runner/job_context.dart
> +  /// Name of last executed task in job.
Use string builder.

2023-09-19 21:34 UTC, Zekfad commented on lib/src/job_runner/job_context.dart
> +\t\tlastTelegramMessageId: $lastTelegramMessageId''';
Use dart_mappable for this.

2023-09-19 21:34 UTC, Zekfad commented on lib/src/micro_ci.dart
> +  ready,
use `initial`, `ready` and `error` states.

2023-09-19 21:34 UTC, Zekfad commented on lib/src/micro_ci.dart
> +  final _serverConfig = ServerConfig.load('.env');
At least use const static for name.

2023-09-19 22:27 UTC, Zekfad requested changes

2023-09-19 22:27 UTC, Zekfad commented on lib/src/micro_ci.dart
> +      _configState = _MicroCIConfigState.error;
Add log entry here.

2023-09-20 19:13 UTC, Zekfad approved these changes
LGTM

2023-09-23 06:11 UTC, closed without merging